### ISSUE TITLE
max CPU temperature issue

### ISSUE THREAD

**Issue by gatsu1984** [nobodysu/zabbix-mini-IPMI#3] opened 2017-07-05 01:43 UTC
hello,
trying to use your zabbix-mini-IMPI, but getting error on Maximum CPU Temperature, and as i understand since it cant get max cpu temp, it also not getting other info by sender.
This is from server log:
"example.org:temp.cpu[max]" changed: Received value [zabbix_sender.exe [376]: invalid parameter ""44] is not suitable for value type [Numeric (unsigned)] and data type [Decimal].
So it shows max temp, but with it also showing some sender error about invalid parameters and not working couse of this.
on server:
root@zabbixserver:~# zabbix_get -s 192.168.1.15 -k temp.cpu[max]
zabbix_sender.exe [1592]: invalid parameter ""
45

script on computer:
C:\zabbix\scripts>zabbix-ohmr-wrapper.py
zabbix_sender.exe [1452]: invalid parameter ""
44

C:\zabbix\scripts>zabbix-ohmr-wrapper.py -v
boardTempRe: [('35', '0'), ('7', '1'), ('41', '2')]
cpuTempRe: [('44', '0'), ('43', '1')]
gpuTempRe: [('52', '0')]
boardFanRe: [('2934', '1')]
voltageRe: [('1.248', '0'), ('1.888', '1'), ('3.344', '2'), ('3.296', '3'),
('0.176', '4'), ('1.736', '5'), ('1.392', '6'), ('3.472', '7')]

ServerActive config value:
192.168.1.155

Hostname config value:
example.org

zabbix_sender path:
C:/zabbix/bin/win64/zabbix_sender.exe

Data sent to zabbix sender:

temp.brd[0] 35
temp.brd[1] 7
temp.brd[2] 41
temp.brd[max] 41
temp.cpu[0] 44
temp.cpu[1] 43
temp.gpu[0] 52
temp.gpu[max] 52
fan.brd[1] 2934
vlt.brd[0] 1.248
vlt.brd[1] 1.888
vlt.brd[2] 3.344
vlt.brd[3] 3.296
vlt.brd[4] 0.176
vlt.brd[5] 1.736
vlt.brd[6] 1.392
vlt.brd[7] 3.472
zabbix_sender.exe [1820]: DEBUG: answer [{"response":"success","info":"processed
: 17; failed: 0; total: 17; seconds spent: 0.000263"}]
44

when i runing script by hand on computer , it sends other temperature info but not max temp

can you help me somehow?
thx

**Comment by nobody43** [comment] 2017-07-05 09:47
Good day.
What about your userparameter? No spaces there? Quoting must be a proper way:
`UserParameter=temp.disk[*], python "c:\zabbix-agent\scripts\temp-disk.py" "$1"`

**Comment by gatsu1984** [comment] 2017-07-05 14:30
userparameters exact as in your file. i just copied it.  

temp.disk is working normall, only temp.cpu working strange

**Comment by nobody43** [comment] 2017-07-05 14:38
Please replace the line that I provided (quote the arguments) and restart the agent.
If that doesn't help try using 32bit sender.

**Comment by gatsu1984** [comment] 2017-07-05 14:47
same.

with 32 bit sender

 29515:20170705:174639.161 item "example.org:temp.cpu[max]" became not supported: Received value [zabbix_sender.exe [1676]: invalid parameter ""4] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]

this is from config
UserParameter=smartctl.discovery[*] , python "C:\zabbix\scripts\smartctl-lld.py" "$1" "$2"
UserParameter=temp.cpu[*], python "c:\zabbix\scripts\zabbix-ohmr-wrapper.py"
UserParameter=temp.disk[*], python "c:\zabbix-agent\scripts\temp-disk.py" "$1"

**Comment by nobody43** [comment] 2017-07-05 15:00
Please attach your configuration from zabbix-ohmr-wrapper.py (header) and whole zabbix config file.

**Comment by gatsu1984** [comment] 2017-07-05 15:23
[ohmr-wrapper.txt](https://github.com/nobodysu/zabbix-mini-IPMI/files/1125158/ohmr-wrapper.txt)


[zabbix_agentd.txt](https://github.com/nobodysu/zabbix-mini-IPMI/files/1125162/zabbix_agentd.txt)

**Comment by nobody43** [comment] 2017-07-05 15:35
Try changing line 116 of ohmr-wrapper to this:
`senderProc = subprocess.Popen([senderPath, '-c', agentConf, '-i', '-'], stdin=subprocess.PIPE, stdout=subprocess.DEVNULL, universal_newlines=True)`
(remove isDebug)

**Comment by gatsu1984** [comment] 2017-07-05 15:52
on windows, after deleting  isDebug, temp.cpu[max] working normal, but not getting other items

on zabbix server on linux , after deleting isDebug, getting  temp.cpu[max]  and temp.cpu[0]  temp.cpu[1]  by sender

**Comment by nobody43** [comment] 2017-07-05 18:16
`zabbix_agentd.exe -V`
`zabbix_sender.exe -V`
?

**Comment by gatsu1984** [comment] 2017-07-05 18:23
c:\zabbix\bin\win64>zabbix_agentd.exe -V
zabbix_agentd Win64 (service) (Zabbix) 3.2.0
Revision 62444 13 September 2016, compilation time: Sep 12 2016 15:28:10

Copyright (C) 2016 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

c:\zabbix\bin\win64>zabbix_sender.exe -V
zabbix_sender (Zabbix) 3.2.0
Revision 62444 13 September 2016, compilation time: Sep 12 2016 15:28:10

Copyright (C) 2016 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

**Comment by gatsu1984** [comment] 2017-07-05 18:24
on zabbix server

root@zabbixserver:/etc/zabbix/scripts# zabbix_agentd -V
zabbix_agentd (daemon) (Zabbix) 3.2.6
Revision 67849 4 May 2017, compilation time: May  6 2017 01:09:33

Copyright (C) 2017 Zabbix SIA
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it according to
the license. There is NO WARRANTY, to the extent permitted by law.

**Comment by nobody43** [comment] 2017-07-05 18:28
Also `python -V` please.

**Comment by gatsu1984** [comment] 2017-07-05 18:35
windows
c:\zabbix\bin\win64>python -V
Python 3.6.1

but also have computers with 3.4 that working same as this

linux
root@zabbixserver:/etc/zabbix/scripts# python -V
Python 2.7.12
it shows 2.7 but 3.5 also installed

**Comment by nobody43** [comment] 2017-07-07 00:09
Unfortunately I can't reproduce this behavior with 3.2 agent/sender. Are you sure that `vlt` and `fan` is present on machine and still missing (beside present `temp.cpu*`)?

**Comment by gatsu1984** [comment] 2017-07-07 15:31
yes im sure that its present, becouse i can get it if i wil run python script by hand with "-v" 

since i dont know python i fixed it in this way

i didnt delete isDebug and ad this in senderProc : stderr=subprocess.DEVNULL

senderProc = subprocess.Popen([senderPath, isDebug, '-c', agentConf, '-i', '-'], stdin=subprocess.PIPE, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, universal_newlines=True)

and put this in agent config so it cut all except temp max after runing script with -v

UserParameter=temp.cpu[*],for /F "eol=- skip=19" %a in ('c:\zabbix\scripts\zabbix-ohmr-wrapper.py -v') do @echo %a

this way all items sending for me

**Comment by nobody43** [comment] 2017-07-07 15:40
Glad you sorted it out. I planned to rewrite this script in more convenient, LLD-way in a couple of months. Most likely it will be fixed there.

**Comment by gatsu1984** [comment] 2017-07-07 15:41
good to hear it :)

**Comment by nobody43** [comment] 2017-11-06 17:31
Fixed in v2.

**Closed as completed by nobody43** 2017-11-06 17:31 UTC
